name: Generate terraform docs

on:
  pull_request:

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Clone the repository
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        persist-credentials: false
    - name: Render terraform docs and fail on diff
      uses: step-security/terraform-docs-action@009ca67cbaa19496e50a6691ce86a26d49cb0b57 # v1.4.6
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        fail-on-diff: "true"
    - name: Dump README
      if: failure()
      run: |
        cat README.md
